import Head from 'next/head';
import Link from 'next/link';
import Layout from '@/components/layout/layout.component';

import 'animate.css';
const Home = () => {
  return (
    <>
      <Head>
        <title>LTC | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <section className='mt-20'>
          <h1 className='text-6xl font-bold mb-2 text-center'>Learn To Code</h1>
          <p className='text-xl text-center animate__animated animate__fadeInLeft'>
            Learn to code <span className='html-logo-color'>HTML</span>,
            <span className='css-logo-color'>CSS</span>, and
            <span className='js-logo-color'>JS</span>.
          </p>
        </section>
        <section className='mt-20'>
          <div className='animate__animated animate__bounce text-2xl'>👇</div>
          <h2 className='text-3xl mb-4 font-medium'>Want to learn to code?</h2>
          <p className='max-w-prose'>
            Are you having a tough time coding, or trying to get your feet wet
            with coding we have your back. We got tutorials covering HTML, CSS,
            and JavaScript which will set you up with the tools needed to become
            coders.
          </p>
        </section>
        <section className='flex flex-col lg:flex-row justify-around mt-20'>
          <Link href='/learn-html'>
            <section className='h-52 animate__animated animate__fadeInLeft'>
              <h2 className='text-3xl font-medium mb-2'>
                Learn <span className='html-logo-color'>&lt;</span>HTML
                <span className='html-logo-color'>&gt;</span>
              </h2>
              <p>Learn the basics of HTML, and get up and running.</p>
            </section>
          </Link>
          <Link href='/learn-css'>
            <section className='h-52 animate__animated animate__fadeInLeft'>
              <h2 className='text-3xl font-medium mb-2'>
                Learn <span className='css-logo-color'>{'{'} </span>css
                <span className='css-logo-color'> {'}'}</span>
              </h2>
              <p>Learn the basics of CSS, and get up and running.</p>
            </section>
          </Link>
          <section className='h-52 animate__animated animate__fadeInLeft'>
            <h2 className='text-3xl font-medium mb-2'>
              Learn <span className='js-logo-color'>{'{'} </span>js
              <span className='js-logo-color'> {'}'}</span>
            </h2>
            <p>Learn the basics of JS, and get up and running.</p>
          </section>
        </section>
      </Layout>
    </>
  );
};

export default Home;
